---
title: "Low birthweight and smoking"
author: "Cattaneo"
date: "5/20/2026"
date-modified: "5/23/2026"
categories: [Causal I]
---

## Source

Excerpt of data from Cattaneo (2010) Journal of Econometrics 155: 138-154 used in the Stata [Treaetment Effects](https://www.stata-press.com/data/r19/causal.html) reference manuals starting in Stata 13 and in use through Stata 19


## Dataset description 

### Features

The data are a subset of that originally described by Almond 2005 (Quarterly Journal of Economics, 120 (2005), pp. 1031-1083) as being from the 1989-1991 Linked National Natality-Mortality Detail Files used for a study focusing on smoking during pregnancy and birth weight for the 497,139 singleton births in Pennsylvania between 1989 and 1991. Pennsylvania was chosen since there was complete smoking information for over 95 percent of the mothers in 1989-1991. In the singleton sample, about 21 percent of Pennsylvanian women report smoking during pregnancy in this time period.

use directly in code

```stata
use https://www.stata-press.com/data/r16/cattaneo2 , clear
```

Published example of causal inference methods paper using this dataset. ([Ghosh 2021 Stat Sin](https://pmc.ncbi.nlm.nih.gov/articles/PMC8439424/#S21))

### Variables

```
Contains data from https://www.stata-press.com/data/r16/cattaneo2.dta
. codebook,compact

Variable     Obs Unique      Mean  Min   Max  Label
-------------------------------------------------------------------------------------------------------------------------
bweight     4642    732   3361.68  340  5500  infant birthweight (grams)
mmarried    4642      2  .6996984    0     1  1 if mother married
mhisp       4642      2  .0340371    0     1  1 if mother hispanic
fhisp       4642      2   .037053    0     1  1 if father hispanic
foreign     4642      2  .0534252    0     1  1 if mother born abroad
alcohol     4642      2  .0323137    0     1  1 if alcohol consumed during pregnancy
deadkids    4642      2   .259371    0     1  previous births where newborn died
mage        4642     33  26.50452   13    45  mother's age
medu        4642     18  12.68957    0    17  mother's education attainment
fage        4642     46  27.26713    0    60  father's age
fedu        4642     17   12.3072    0    17  father's education attainment
nprenatal   4642     30  10.75808    0    40  number of prenatal care visits
monthslb    4642    173  23.07497    0   272  months since last birth
order       4642     12  1.892072    0    12  order of birth of the infant
msmoke      4642      4  .3996122    0     3  cigarettes smoked during pregnancy
mbsmoke     4642      2  .1861267    0     1  1 if mother smoked
mrace       4642      2   .840586    0     1  1 if mother is white
frace       4642      2  .8136579    0     1  1 if father is white
prenatal    4642      4  1.201853    0     3  trimester of first prenatal care visit
birthmonth  4642     12  6.540069    1    12  month of birth
lbweight    4642      2  .0603188    0     1  1 if low birthweight baby
fbaby       4642      2  .4379578    0     1  1 if first baby
prenatal1   4642      2  .8013787    0     1  1 if first prenatal visit in 1 trimester
-------------------------------------------------------------------------------------------------------------------------

```
