project:
  type: website
  output-dir: docs

website:
  title: "NCSP methods class website"
  search: true
  repo-url: https://github.com/tphofer/ncsp-hhcr/ 
  repo-actions: [edit]
  site-url: https://tphofer.github.io/ncsp-hhcr/
  sidebar:
    collapse-level: 2
    pinned: true
    contents:
      - index.qmd
      - data.qmd
author: "TPH"
date: "today"
code-fold: true
number-depth: 3
toc: true
toc-depth: 5
toc-location: right
reference-location: margin
format:
  html:
    html-math-method: 
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
    theme: 
      - cosmo
      - custom_doc.scss
    grid:
      sidebar-width: 210px
      body-width: 900px



